# SADNxAI CI/CD Pipeline
# Only runs on main branch

when:
  - branch: main
    event: push

steps:
  - name: deploy
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "D:/IAU/skill forge/Sadn-bank/SADNxAI:/host-app"
    commands:
      - apk add --no-cache rsync
      - rsync -av --delete --exclude='.git' --exclude='node_modules' --exclude='.next' --exclude='storage' /woodpecker/src/github.com/taurusn/SADNxAI/ /host-app/
      - cd /host-app
      - docker compose down frontend
      - docker compose up -d --build frontend
      - echo "Frontend redeployed!"
