# SADNxAI CI/CD Pipeline
# - All branches: lint + type-check
# - main branch: deploy (git pull + restart)

steps:
  # ============================================
  # VALIDATION (all branches)
  # ============================================

  lint-frontend:
    image: node:20-alpine
    commands:
      - cd frontend
      - npm ci --silent
      - npm run lint
      - echo "Frontend lint passed"

  typecheck-frontend:
    image: node:20-alpine
    commands:
      - cd frontend
      - npm ci --silent
      - npx tsc --noEmit
      - echo "Frontend type-check passed"

  lint-backend:
    image: python:3.11-slim
    commands:
      - pip install ruff --quiet
      - ruff check chat-service/ masking-service/ validation-service/ --ignore E501
      - echo "Backend lint passed"

  # ============================================
  # DEPLOY (main branch only)
  # ============================================

  deploy:
    image: docker:24-cli
    when:
      branch: main
      event: push
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /d/IAU/skill forge/Sadn-bank/SADNxAI:/app
    commands:
      - cd /app
      - git pull origin main
      - docker compose down
      - docker compose up -d --build
      - echo "Deployment complete"

  notify-success:
    image: alpine
    when:
      branch: main
      event: push
      status: success
    commands:
      - echo "SADNxAI deployed successfully!"
      - echo "Frontend: https://sadnxai.sadn.site"
      - echo "API: https://sadnxaiapi.sadn.site"

  notify-failure:
    image: alpine
    when:
      status: failure
    commands:
      - echo "Pipeline failed! Check logs above."
