# SADNxAI CI/CD Pipeline
# Only runs on main branch - minimal version

when:
  - branch: main
    event: push

steps:
  - name: deploy
    image: alpine
    commands:
      - echo "Deploying SADNxAI..."
      - echo "Done!"
