# SADNxAI CI/CD Pipeline  
# Only runs on main branch

when:
  - branch: main
    event: push

steps:
  - name: lint-backend
    image: python:3.11-slim
    commands:
      - python -m pip install ruff --quiet --timeout 30 --retries 2
      - ruff check chat-service/ masking-service/ validation-service/ --ignore E501
      - echo "Lint passed"

  - name: deploy
    image: alpine
    commands:
      - echo "Deploy complete"
