# SADNxAI CI/CD Pipeline
# Only runs on main branch

when:
  - branch: main
    event: push

steps:
  - name: deploy
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "D:/IAU/skill forge/Sadn-bank/SADNxAI:/app"
    commands:
      - apk add --no-cache git
      - cd /app
      - git config --global --add safe.directory /app
      - git pull origin main
      - docker compose down frontend
      - docker compose up -d --build frontend
      - echo "Frontend redeployed!"
