# SADNxAI CI/CD Pipeline
# Only runs on main branch

when:
  - branch: main
    event: push

steps:
  - name: deploy
    image: alpine/git:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "D:/IAU/skill forge/Sadn-bank/SADNxAI:/app"
      - "C:/Users/sei/.ssh:/ssh-keys:ro"
    commands:
      - mkdir -p /root/.ssh
      - cp /ssh-keys/* /root/.ssh/
      - chmod 600 /root/.ssh/id_ed25519
      - cd /app
      - git config --global --add safe.directory /app
      - git fetch origin main
      - git reset --hard origin/main
      - echo "Code updated!"

  - name: rebuild
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "D:/IAU/skill forge/Sadn-bank/SADNxAI:/app"
    commands:
      - cd /app
      - docker compose -p sadnxai up -d --build frontend chat-service
      - echo "Frontend and chat-service redeployed!"
