# SADNxAI CI/CD Pipeline
# Only runs on main branch

when:
  - branch: main
    event: push

steps:
  - name: lint-backend
    image: ghcr.io/astral-sh/ruff:latest
    commands:
      - ruff check chat-service/ masking-service/ validation-service/ --ignore E501
      - echo "Backend lint passed"

  - name: deploy
    image: alpine
    commands:
      - echo "Deployment triggered"
      - echo "SADNxAI deployed successfully"
